version: '3'
services:
    db:
        image: mysql:5.7
        container_name: my-db
        ports:
            - "3308:3306"
        # environment:
        #     - MYSQL_ROOT_PASSWORD=12345678
        #     - SHOW=true
        env_file:
            - env.txt
        volumes:
            - my_volume:/var/lib/mysql
        networks:
            - new_network
volumes:
    my_volume:
networks:
    new_network: